# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 808106aebb7d7f302e059326a9956cbb1b6ee349db18e1faefea04785c3a240aedbe98754ed74c19030c16d0228ae2dbd2f4f65439bca435c36cc4a18d3fc1ef

test:
  secret_key_base: ffd2d4f5510bde5ace479031ae27f22944d8346ccee0c4ae58bffb0c610c8f043e42b0ba739c502caa8016de9e812bcc047ea57c5975c2144af9545c9838f90e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
